steps:
  - name: "gcr.io/$PROJECT_ID/makepkg"
    args:
      - "-c"
      - >-
        chmod 4755 /bin/sudo &&
        echo 'nobody ALL=(ALL) NOPASSWD: /bin/sudo' >> /etc/sudoers &&
        cp -r /workspace/media-automount /tmp/build &&
        chmod -R a=rwx /tmp/build &&
        cd /tmp/build && 
        sudo -u nobody makepkg -s &&
        cp *.pkg.tar* /workspace/media-automount &&
        cd /workspace/media-automount && 
        ls -al
