steps:
  - name: "gcr.io/$PROJECT_ID/makepkg"
    args:
      - "-c"
      - >-
        cp /workspace/media-automount /tmp/build &&
        chmod -R a=rwx /tmp/build &&
        cd /tmp/build && 
        sudo -u nobody makepkg &&
        cp *.pkg.tar* /workspace/media-automount &&
        cd /workspace/media-automount && 
        ls -al
