steps:
  - name: "gcr.io/cloud-builders/gsutil"
    entrypoint: "/bin/sh"
    args:
      - "-c"
      - "chmod -R +w /workspace"
  - name: "gcr.io/$PROJECT_ID/makepkg"
  # - name: "gcr.io/cloud-builders/gsutil"
  #   args:
  #     - "cp"
  #     - ""
